let tl = gsap.timeline()
    .to("#layer1", { x: -80 })
    .to("#path4245", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2816", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2821", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2821-1", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2821-4", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2821-9", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2821-8", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#rect2821-2", { strokeWidth: 5, stroke: "gold", repeat: -1 })
    .to("#path4141-1", { strokeWidth: 5, stroke: "blue", repeat: -1 })
    .to("#path3967-4", { strokeWidth: 5, stroke: "blue", repeat: -1 })
    .to("#path4904", { strokeWidth: 5, stroke: "blue", repeat: -1 })
    .to("#path4141", { strokeWidth: 5, stroke: "blue", repeat: -1 })